/**
 * Normalise the configured origin.
 *
 * A trailing slash in the env var is an easy thing to type and produces `//`
 * in every canonical, hreflang and sitemap URL — which crawlers read as a
 * different page than the one actually served. Strip it here rather than
 * relying on whoever sets the variable to get it right.
 */
function normaliseOrigin(value: string): string {
  return value.trim().replace(/\/+$/, "");
}

export const SITE = {
  name: "MsgLens",
  /** Update to the production domain before the first deploy. */
  url: normaliseOrigin(process.env.NEXT_PUBLIC_SITE_URL ?? "https://msglens.app"),
  tagline: "Open .msg files in your browser",
  /**
   * AdSense publisher id.
   *
   * Committed rather than left to the environment, for the same reason as the
   * URL above: it is public by construction — it appears in the <head> of
   * every page and in ads.txt — and an unset build variable removes the
   * verification snippet from the live site without failing the build or
   * reporting anything. That is a bad trade for a value with no secrecy.
   *
   * The environment still wins if set, so a fork or a staging build can
   * override it.
   */
  adsenseClient: process.env.NEXT_PUBLIC_ADSENSE_CLIENT ?? "ca-pub-6812887872244325",
  /**
   * Who operates the site, as distinct from what the site is called.
   *
   * These were the same string until payments existed. They cannot be now: a
   * card statement and a receipt carry the seller's name, and a customer who
   * cannot find that name on the site they bought from calls their bank rather
   * than writing to us. Product name stays MsgLens; the entity is this.
   */
  operator: "YingYen Dev",
  /**
   * The card-statement string, which is not the operator name and cannot be.
   *
   * Paddle caps the descriptor at ten characters, uppercase only, so the space
   * and the casing are gone. Held separately because the two appear in
   * different places — a receipt says one, a bank statement says the other —
   * and a customer checking an unfamiliar charge may be holding either.
   */
  statementDescriptor: "YINGYENDEV",
  /**
   * The public source. Linked from the footer beside the privacy claim, because
   * "nothing is uploaded" is checkable rather than something to be trusted.
   */
  repo: "https://github.com/AndyLiu0427/msglens",
  contactEmail: "hello@msglens.app",
  /** Files larger than this are rejected before parsing to protect the tab. */
  maxFileBytes: 100 * 1024 * 1024,
  maxFiles: 50,
  /**
   * Demo message served from our own origin. Generated by
   * scripts/make-sample-msg.mts — a real .msg so the demo goes through the
   * same parser as a user's file, with entirely fictional contents.
   */
  sampleFile: "/sample-message.msg",
  /**
   * AdSense ad unit ids, per placement.
   *
   * Empty until the units are created in the AdSense dashboard — an <AdSlot>
   * with no id renders nothing at all, rather than requesting a unit that does
   * not exist. Auto ads need none of these; they run off the head script alone.
   */
  adSlots: {
    homeLeaderboard: "",
    articleTop: "",
    articleFooter: "",
    faqTop: "",
    viewerFooter: "",
  },
} as const;

export const LOCALES = ["en", "zh"] as const;
export type Locale = (typeof LOCALES)[number];
export const DEFAULT_LOCALE: Locale = "en";

/**
 * Map a route path (without locale prefix) to its absolute URL for a locale.
 *
 * Emits a trailing slash to match `trailingSlash: true` in next.config, so the
 * URLs in the sitemap are byte-identical to the canonical tags on the pages
 * they point at. A mismatch here reads to a crawler as two distinct URLs.
 */
export function localizedUrl(path: string, locale: Locale): string {
  const clean = path === "/" ? "" : path.replace(/^\/|\/$/g, "");
  const prefix = locale === DEFAULT_LOCALE ? "" : `/${locale}`;
  return `${SITE.url}${prefix}${clean ? `/${clean}` : ""}/`;
}

export function localizedPath(path: string, locale: Locale): string {
  const clean = path === "/" ? "" : path.replace(/^\/|\/$/g, "");
  const prefix = locale === DEFAULT_LOCALE ? "" : `/${locale}`;
  return `${prefix}${clean ? `/${clean}` : ""}` || "/";
}

/** Every content route, used for the sitemap and hreflang alternates. */
export const ROUTES = [
  "/",
  "/how-to-open-msg-files",
  "/msg-file-wont-open",
  "/open-winmail-dat",
  "/msg-to-eml",
  "/what-is-a-msg-file",
  "/outlook-msg-no-html-body",
  "/msg-vs-eml",
  "/convert-msg-to-pdf",
  "/pricing",
  "/faq",
  "/about",
  "/contact",
  "/privacy",
  "/terms",
] as const;
